### ISSUE TITLE
I don't know how to use that ?

### ISSUE THREAD

**Issue by CtrlcCtrlVElite** [TimvanDijkhuizen/SpigotUtils#2]
`    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://papermc.io/repo/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.17-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>timvandijkhuizen</groupId>
            <artifactId>spigot-utils</artifactId>
            <version>1.2.4</version>
        </dependency>
    </dependencies>
</project>
`
<dependency>
            <groupId>timvandijkhuizen</groupId>
            <artifactId>spigot-utils</artifactId>
            <version>1.2.4</version>
        </dependency>                                                         that is red

we don't need to add something in </repositories>

**Comment by tim-van-dijkhuizen** [comment]
This plugin currently isn't available through the central maven repository. However, you can get it from GitHub packages.

1. Add GitHub to your repositories:
```
<repository>
    <id>github</id>
    <url>https://maven.pkg.github.com/timvandijkhuizen/*</url>
</repository>
```

2. Set-up GitHub authentication
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages

More information: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#installing-a-package

I would like to make it available through maven central at some point. Unfortunately, I don't have a lot of free time, so it probably won't be happening any time soon.

**Comment by CtrlcCtrlVElite** [comment]
ok thx
