### ISSUE TITLE
The pagedmenu of menu is not work

### ISSUE THREAD

**Issue by CtrlcCtrlVElite** [TimvanDijkhuizen/SpigotUtils#5]
Paged menu

```
PagedMenu menu = new PagedMenu("Test menu");

// Add buttons
for (int i = 1; i <= 42; ++i) {
    MenuItemBuilder item = new MenuItemBuilder(XMaterial.APPLE);

    item.setName("Item " + i);

    menu.addPagedItem(item);
}

menu.open(player);
```
this is copy in your example , but when I copy it in my program ,it  doesn't work ,(my client is not error) click the 'next page button' or 'previons page button' is not work ,the same thing appears in setClickListener.

My client is paper 1.17

**Comment by tim-van-dijkhuizen** [comment]
When writing the documentation, I forgot to mention that you need to register the MenuService, in order for menu's to handle clicks. I've just updated the documentation to include an extra step. Please let me know if this resolves your issue.

https://github.com/TimvanDijkhuizen/SpigotUtils/blob/master/docs/MENU.md#register-menuservice

**Comment by Peter1224** [comment]
I add a new file to copy the the Register MenuService ,Do I need to add something on other file?

**Comment by Peter1224** [comment]
我添加了一个新文件来复制 Register MenuService ，我需要在其他文件上添加一些东西吗？因为它不起作用

**Comment by CtrlcCtrlVElite** [comment]
I add a new file to copy the the Register MenuService ,Do I need to add something on other file?because it's not work

**Comment by CtrlcCtrlVElite** [comment]
I need to add the Register MenuService to where. @TimvanDijkhuizen

**Comment by tim-van-dijkhuizen** [comment]
The recommended way to register a service is using the plugin API. [This example](https://github.com/TimvanDijkhuizen/SpigotUtils/blob/master/docs/MENU.md#register-menuservice) shows how to register the MenuService using the plugin API. For more information about the plugin API, check [this link](https://github.com/TimvanDijkhuizen/SpigotUtils/blob/master/docs/PLUGIN.md). To see the plugin API in action, take a look at the [main class from my Minecraft Commerce plugin](https://github.com/TimvanDijkhuizen/MinecraftCommerce/blob/master/src/nl/timvandijkhuizen/commerce/Commerce.java).

**Comment by CtrlcCtrlVElite** [comment]
So I still won't use... 😥

**Comment by tim-van-dijkhuizen** [comment]
Another, less clean way to register, is to create an instance of the MenuService and register it as a listener.

Example:
```java
getServer().getPluginManager().registerEvents(new MenuService(), this);
```

**Comment by CtrlcCtrlVElite** [comment]
it's work ,thx
